// Arrays with keys data

const engRow0 = [['`', '~', '`', '~'],
  ['1', '!', '1', '!'],
  ['2', '@', '2', '@'],
  ['3', '#', '3', '#'],
  ['4', '$', '4', '$'],
  ['5', '%', '5', '%'],
  ['6', '^', '6', '^'],
  ['7', '&', '7', '&'],
  ['8', '*', '8', '*'],
  ['9', '(', '9', '('],
  ['0', ')', '0', ')'],
  ['-', '_', '-', '_'],
  ['=', '+', '=', '+'],
  ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
];

const engRow1 = [['Tab', 'Tab', 'Tab', 'Tab'],
  ['q', 'Q', 'Q', 'q'],
  ['w', 'W', 'W', 'w'],
  ['e', 'E', 'E', 'e'],
  ['r', 'R', 'R', 'r'],
  ['t', 'T', 'T', 't'],
  ['y', 'Y', 'Y', 'y'],
  ['u', 'U', 'U', 'u'],
  ['i', 'I', 'I', 'i'],
  ['o', 'O', 'O', 'o'],
  ['p', 'P', 'P', 'p'],
  ['[', '{', '[', '{'],
  [']', '}', ']', '}'],
  ['\\', '|', '\\', '|'],
  ['Del', 'Del', 'Del', 'Del'],
];

const engRow2 = [['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  ['a', 'A', 'A', 'a'],
  ['s', 'S', 'S', 's'],
  ['d', 'D', 'D', 'd'],
  ['f', 'F', 'F', 'f'],
  ['g', 'G', 'G', 'g'],
  ['h', 'H', 'H', 'h'],
  ['j', 'J', 'J', 'j'],
  ['k', 'K', 'K', 'k'],
  ['l', 'L', 'L', 'l'],
  [';', ':', ';', ':'],
  ['\'', '"', '\'', '"'],
  ['Enter', 'Enter', 'Enter', 'Enter'],
];

const engRow3 = [['Shift', 'Shift', 'Shift', 'Shift'],
  ['z', 'Z', 'Z', 'z'],
  ['x', 'X', 'X', 'x'],
  ['c', 'C', 'C', 'c'],
  ['v', 'V', 'V', 'v'],
  ['b', 'B', 'B', 'b'],
  ['n', 'N', 'N', 'n'],
  ['m', 'M', 'M', 'm'],
  [',', '<', ',', '<'],
  ['.', '>', '.', '>'],
  ['/', '?', '/', '?'],
  ['▼', 'ArrowUp', 'ArrowUp', 'ArrowUp'],
  ['LShift', 'LShift', 'LShift', 'LShift'],
];

const engRow4 = [['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  ['Win', 'Win', 'Win', 'Win'],
  ['Alt', 'Alt', 'Alt', 'Alt'],
  ['Spacebar', 'Spacebar', 'Spacebar', 'Spacebar'],
  ['Alt', 'Alt', 'Alt', 'Alt'],
  ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  ['^', 'ArrowLeft', 'ArrowLeft', 'ArrowLeft'],
  ['▼', 'ArrowDown', 'ArrowDown', 'ArrowDown'],
  ['>', 'ArrowRight', 'ArrowRight', 'ArrowRight'],
  ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
];

const rusRow0 = [
  ['Ё', 'ё', 'Ё', 'ё'],
  ['!', '1', '!', '1'],
  ['"', '2', '"', '2'],
  ['№', '3', '№', '3'],
  [';', '4', ';', '4'],
  ['%', '5', '%', '5'],
  [':', '6', ':', '6'],
  ['?', '7', '?', '7'],
  ['*', '8', '*', '8'],
  ['(', '9', '(', '9'],
  [')', '0', ')', '0'],
  ['_', '-', '_', '-'],
  ['+', '=', '+', '='],
  ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
];

const rusRow1 = [
  ['Tab', 'Tab', 'Tab', 'Tab'],
  ['Й', 'й', 'Й', 'й'],
  ['Ц', 'ц', 'Ц', 'ц'],
  ['У', 'у', 'У', 'у'],
  ['К', 'к', 'К', 'к'],
  ['Е', 'е', 'Е', 'е'],
  ['Н', 'н', 'Н', 'н'],
  ['Г', 'г', 'Г', 'г'],
  ['Ш', 'ш', 'Ш', 'ш'],
  ['Щ', 'щ', 'Щ', 'щ'],
  ['З', 'з', 'З', 'з'],
  ['Х', 'х', 'Х', 'х'],
  ['Ъ', 'ъ', 'Ъ', 'ъ'],
  ['\\', '/', '\\', '/'],
  ['Del', 'Del', 'Del', 'Del'],
];
const rusRow2 = [
  ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  ['ф', 'Ф', 'Ф', 'ф'],
  ['ы', 'Ы', 'Ы', 'ы'],
  ['в', 'В', 'В', 'в'],
  ['а', 'А', 'А', 'а'],
  ['п', 'П', 'П', 'п'],
  ['р', 'Р', 'Р', 'р'],
  ['о', 'О', 'О', 'о'],
  ['л', 'Л', 'Л', 'л'],
  ['д', 'Д', 'Д', 'д'],
  ['ж', 'Ж', 'Ж', 'ж'],
  ['э', 'Э', 'Э', 'э'],
  ['Enter', 'Enter', 'Enter', 'Enter'],
];
const rusRow3 = [
  ['Shift', 'Shift', 'Shift', 'Shift'],
  ['я', 'Я', 'Я', 'я'],
  ['ч', 'Ч', 'Ч', 'ч'],
  ['с', 'С', 'С', 'с'],
  ['м', 'М', 'М', 'м'],
  ['и', 'И', 'И', 'и'],
  ['т', 'Т', 'Т', 'т'],
  ['ь', 'Ь', 'Ь', 'ь'],
  ['б', 'Б', 'Б', 'б'],
  ['ю', 'Ю', 'Ю', 'ю'],
  ['.', ',', '.', ','],
  ['ArrowUp', 'ArrowUp', 'ArrowUp', 'ArrowUp'],
  ['LShift', 'LShift', 'LShift', 'LShift'],
];

const rusRow4 = [
  ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  ['Win', 'Win', 'Win', 'Win'],
  ['Alt', 'Alt', 'Alt', 'Alt'],
  ['Spacebar', 'Spacebar', 'Spacebar', 'Spacebar'],
  ['Alt', 'Alt', 'Alt', 'Alt'],
  ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  ['ArrowLeft', 'ArrowLeft', 'ArrowLeft', 'ArrowLeft'],
  ['ArrowDown', 'ArrowDown', 'ArrowDown', 'ArrowDown'],
  ['ArrowRight', 'ArrowRight', 'ArrowRight', 'ArrowRight'],
  ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
];

export {
  engRow0, engRow1, engRow2, engRow3, engRow4,
  rusRow0, rusRow1, rusRow2, rusRow3, rusRow4,
};
