// Arrays with keys data

const engRow0 = [['`', '~', '`', '~'],
  ['1', '!', '1', '!'],
  ['2', '@', '2', '@'],
  ['3', '#', '3', '#'],
  ['4', '$', '4', '$'],
  ['5', '%', '5', '%'],
  ['6', '^', '6', '^'],
  ['7', '&', '7', '&'],
  ['8', '*', '8', '*'],
  ['9', '(', '9', '('],
  ['0', ')', '0', ')'],
  ['-', '_', '-', '_'],
  ['=', '+', '=', '+'],
  ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
];

const engRow1 = [['Tab', 'Tab', 'Tab', 'Tab'],
  ['q', 'Q', 'Q', 'q'],
  ['w', 'W', 'W', 'w'],
  ['e', 'E', 'E', 'e'],
  ['r', 'R', 'R', 'r'],
  ['t', 'T', 'T', 't'],
  ['y', 'Y', 'Y', 'y'],
  ['u', 'U', 'U', 'u'],
  ['i', 'I', 'I', 'i'],
  ['o', 'O', 'O', 'o'],
  ['p', 'P', 'P', 'p'],
  ['[', '{', '[', '{'],
  [']', '}', ']', '}'],
  ['\\', '|', '\\', '|'],
  ['Delete', 'Delete', 'Delete', 'Delete'],
];

const engRow2 = [['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  ['a', 'A', 'A', 'a'],
  ['s', 'S', 'S', 's'],
  ['d', 'D', 'D', 'd'],
  ['f', 'F', 'F', 'f'],
  ['g', 'G', 'G', 'g'],
  ['h', 'H', 'H', 'h'],
  ['j', 'J', 'J', 'j'],
  ['k', 'K', 'K', 'k'],
  ['l', 'L', 'L', 'l'],
  [';', ':', ';', ':'],
  ['\'', '"', '\'', '"'],
  ['Enter', 'Enter', 'Enter', 'Enter'],
];

const engRow3 = [['ShiftLeft', 'ShiftLeft', 'ShiftLeft', 'ShiftLeft'],
  ['z', 'Z', 'Z', 'z'],
  ['x', 'X', 'X', 'x'],
  ['c', 'C', 'C', 'c'],
  ['v', 'V', 'V', 'v'],
  ['b', 'B', 'B', 'b'],
  ['n', 'N', 'N', 'n'],
  ['m', 'M', 'M', 'm'],
  [',', '<', ',', '<'],
  ['.', '>', '.', '>'],
  ['/', '?', '/', '?'],
  ['ArrowUp', 'ArrowUp', 'ArrowUp', 'ArrowUp'],
  ['ShiftRight', 'ShiftRight', 'ShiftRight', 'ShiftRight'],
];

const engRow4 = [['ControlLeft', 'ControlLeft', 'ControlLeft', 'ControlLeft'],
  ['MetaLeft', 'MetaLeft', 'MetaLeft', 'MetaLeft'],
  ['AltLeft', 'AltLeft', 'AltLeft', 'AltLeft'],
  ['Space', 'Space', 'Space', 'Space'],
  ['AltRight', 'AltRight', 'AltRight', 'AltRight'],
  ['ArrowLeft', 'ArrowLeft', 'ArrowLeft', 'ArrowLeft'],
  ['ArrowDown', 'ArrowDown', 'ArrowDown', 'ArrowDown'],
  ['ArrowRight', 'ArrowRight', 'ArrowRight', 'ArrowRight'],
  ['ControlRight', 'ControlRight', 'ControlRight', 'ControlRight'],
];

const rusRow0 = [
  ['ё', 'Ё', 'Ё', 'ё'],
  ['1', '!', '1', '!'],
  ['2', '"', '2', '"'],
  ['3', '№', '3', '№'],
  ['4', ';', '4', ';'],
  ['5', '%', '5', '%'],
  ['6', ':', '6', ':'],
  ['7', '?', '7', '?'],
  ['8', '*', '8', '*'],
  ['9', '(', '9', '('],
  ['0', ')', '0', '('],
  ['-', '_', '-', '_'],
  ['=', '+', '=', '+'],
  ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
];

const rusRow1 = [
  ['Tab', 'Tab', 'Tab', 'Tab'],
  ['й', 'Й', 'Й', 'й'],
  ['ц', 'Ц', 'Ц', 'ц'],
  ['у', 'У', 'У', 'у'],
  ['к', 'К', 'К', 'к'],
  ['е', 'Е', 'Е', 'е'],
  ['н', 'Н', 'Н', 'н'],
  ['г', 'Г', 'Г', 'г'],
  ['ш', 'Ш', 'Ш', 'ш'],
  ['щ', 'Щ', 'Щ', 'щ'],
  ['з', 'З', 'З', 'з'],
  ['х', 'Х', 'Х', 'х'],
  ['ъ', 'Ъ', 'Ъ', 'ъ'],
  ['\\', '/', '\\', '/'],
  ['Delete', 'Delete', 'Delete', 'Delete'],
];
const rusRow2 = [
  ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  ['ф', 'Ф', 'Ф', 'ф'],
  ['ы', 'Ы', 'Ы', 'ы'],
  ['в', 'В', 'В', 'в'],
  ['а', 'А', 'А', 'а'],
  ['п', 'П', 'П', 'п'],
  ['р', 'Р', 'Р', 'р'],
  ['о', 'О', 'О', 'о'],
  ['л', 'Л', 'Л', 'л'],
  ['д', 'Д', 'Д', 'д'],
  ['ж', 'Ж', 'Ж', 'ж'],
  ['э', 'Э', 'Э', 'э'],
  ['Enter', 'Enter', 'Enter', 'Enter'],
];
const rusRow3 = [
  ['ShiftLeft', 'ShiftLeft', 'ShiftLeft', 'ShiftLeft'],
  ['я', 'Я', 'Я', 'я'],
  ['ч', 'Ч', 'Ч', 'ч'],
  ['с', 'С', 'С', 'с'],
  ['м', 'М', 'М', 'м'],
  ['и', 'И', 'И', 'и'],
  ['т', 'Т', 'Т', 'т'],
  ['ь', 'Ь', 'Ь', 'ь'],
  ['б', 'Б', 'Б', 'б'],
  ['ю', 'Ю', 'Ю', 'ю'],
  ['.', ',', '.', ','],
  ['ArrowUp', 'ArrowUp', 'ArrowUp', 'ArrowUp'],
  ['ShiftRight', 'ShiftRight', 'ShiftRight', 'ShiftRight'],
];

const rusRow4 = [
  ['ControlLeft', 'ControlLeft', 'ControlLeft', 'ControlLeft'],
  ['MetaLeft', 'MetaLeft', 'MetaLeft', 'MetaLeft'],
  ['AltLeft', 'AltLeft', 'AltLeft', 'AltLeft'],
  ['Space', 'Space', 'Space', 'Space'],
  ['AltRight', 'AltRight', 'AltRight', 'AltRight'],
  ['ArrowLeft', 'ArrowLeft', 'ArrowLeft', 'ArrowLeft'],
  ['ArrowDown', 'ArrowDown', 'ArrowDown', 'ArrowDown'],
  ['ArrowRight', 'ArrowRight', 'ArrowRight', 'ArrowRight'],
  ['ControlRight', 'ControlRight', 'ControlRight', 'ControlRight'],
];

export {
  engRow0, engRow1, engRow2, engRow3, engRow4,
  rusRow0, rusRow1, rusRow2, rusRow3, rusRow4,
};
